Update integration-pr.yml

diff --git a/.github/workflows/integration-pr.yml b/.github/workflows/integration-pr.yml
--- a/.github/workflows/integration-pr.yml
+++ b/.github/workflows/integration-pr.yml
@@ -62,7 +62,11 @@ jobs:
             - name: "Run tests"
               id: run_tests
               run: |
-                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose > test_results.txt || echo "TEST_FAILED=true" >> $GITHUB_ENV
+                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose > test_results.txt
+                  echo "test_outcome=$?" | tee -a $GITHUB_ENV
+                  if [ "$test_outcome" != "0" ]; then
+                    echo "TEST_FAILED=true" >> $GITHUB_ENV
+                  fi
                   echo "TEST_RESULTS_PATH=test_results.txt" >> $GITHUB_ENV
               shell: bash
 
@@ -84,5 +88,5 @@ jobs:
                       });
 
             - name: Fail if tests failed
-              if: steps.run_tests.outputs.test_exit_code != '0'
+              if: env.TEST_FAILED == 'true'
               run: exit 1
