Update integration-pr.yml

diff --git a/.github/workflows/integration-pr.yml b/.github/workflows/integration-pr.yml
--- a/.github/workflows/integration-pr.yml
+++ b/.github/workflows/integration-pr.yml
@@ -61,11 +61,13 @@ jobs:
 
             - name: "Run tests"
               run: |
-                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose > test_results.txt 2>&1 || true
+                  sf project deploy start --dry-run --manifest changed-sources/package/package.xml --post-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --verbose > test_results.txt 2>&1
+                  echo "test_outcome=$?" >> $GITHUB_ENV
                   echo "TEST_RESULTS_PATH=test_results.txt" >> $GITHUB_ENV
+              shell: bash
+              continue-on-error: true
 
             - name: Post results to PR
-              if: always()
               uses: actions/github-script@v7
               with:
                   github-token: ${{secrets.GITHUB_TOKEN}}
@@ -81,3 +83,9 @@ jobs:
                         repo: context.repo.repo,
                         body: `### Code Scan Results:\n[View Code Scanning Alerts](${codeScanningUrl})\n### Test Results:\n\`\`\`${test_results}\`\`\``
                       });
+
+            - name: Fail workflow if tests failed
+              if: env.test_outcome != '0'
+              run: |
+                  echo "Failing the workflow because tests did not pass."
+                  exit 1
